#pragma once

#include "svd/import_eigen.hpp"  // IWYU pragma: export

// TODO: Jixie.
namespace ax::math {

bool AX_FORCE_INLINE remove_rotation(SvdResultImpl<3, real> & svd) {
  bool has_rotation = false;
  real det_u = svd.U_.determinant();
  real det_v = svd.V_.determinant();
  real L = (svd.U_ * svd.V_.transpose()).determinant();
  if (det_u < 0 && det_v > 0) {
    svd.U_.col(2) *= L;
    has_rotation = true;
  } else if (det_u > 0 && det_v < 0) {
    svd.V_.col(2) *= L;
    has_rotation = true;
  }
  svd.sigma_[2] *= L;
  return has_rotation;
}

bool AX_FORCE_INLINE remove_rotation(SvdResultImpl<2, real> & svd) {
  // XXX: This function is automatically generated by the tool?
  bool has_rotation = false;
  real det_u = svd.U_.determinant();
  real det_v = svd.V_.determinant();
  real L = (svd.U_ * svd.V_.transpose()).determinant();
  if (det_u < 0 && det_v > 0) {
    svd.U_.col(1) *= L;
    has_rotation = true;
  } else if (det_u > 0 && det_v < 0) {
    svd.V_.col(1) *= L;
    has_rotation = true;
  }
  svd.sigma_[1] *= L;
  return has_rotation;
}

}